<?php

namespace AppBundle\Repository;

/**
 * DisponibilitatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilitatRepository extends \Doctrine\ORM\EntityRepository
{
}
